import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen w-full bg-gray-100 flex items-center justify-center py-2 px-4 overflow-hidden">
        <div className="w-full max-w-[420px] h-[calc(100vh-1rem)] bg-[#f8f9fa] rounded-[2.5rem] shadow-2xl overflow-hidden relative border-8 border-gray-900 outline outline-4 outline-gray-200/50 flex flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
